### ISSUE TITLE
MixinNode error during the maven build process.

### ISSUE THREAD

**Issue by malcolmdavis** [bdunn44/FontAwesome-Vaadin#1]
Clean maven project built using vaadin-archetype-application 7.3.6
Java version jdk1.7.0_67
Maven: 3.2.1

During the build process, the following error is displayed

 --- vaadin-maven-plugin:7.3.9:compile-theme (default) @ icrVaadinClient ---
[INFO] Updating theme VAADIN\themes\mytheme
[ERROR] Jan 22, 2015 1:02:13 PM com.vaadin.sass.internal.tree.MixinNode traverse
[ERROR] SEVERE: null
[ERROR] com.vaadin.sass.internal.parser.ParseException: Mixin Definition: _font-awesome not found
[ERROR]     at com.vaadin.sass.internal.visitor.MixinNodeHandler.replaceMixins(MixinNodeHandler.java:42)
[ERROR]     at com.vaadin.sass.internal.visitor.MixinNodeHandler.traverse(MixinNodeHandler.java:34)
[ERROR]     at com.vaadin.sass.internal.tree.MixinNode.traverse(MixinNode.java:115)
[ERROR]     at com.vaadin.sass.internal.tree.controldirective.TemporaryNode.traverse(TemporaryNode.java:71)
[ERROR]     at com.vaadin.sass.internal.visitor.MixinNodeHandler.replaceMixinNode(MixinNodeHandler.java:75)
[ERROR]     at com.vaadin.sass.internal.visitor.MixinNodeHandler.replaceMixins(MixinNodeHandler.java:45)
[ERROR]     at com.vaadin.sass.internal.visitor.MixinNodeHandler.traverse(MixinNodeHandler.java:34)
[ERROR]     at com.vaadin.sass.internal.tree.MixinNode.traverse(MixinNode.java:115)
[ERROR]     at com.vaadin.sass.internal.visitor.BlockNodeHandler.traverse(BlockNodeHandler.java:68)
[ERROR]     at com.vaadin.sass.internal.tree.BlockNode.traverse(BlockNode.java:119)
[ERROR]     at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:213)
[ERROR]     at com.vaadin.sass.internal.tree.Node.traverseChildren(Node.java:200)
[ERROR]     at com.vaadin.sass.internal.ScssStylesheet.traverse(ScssStylesheet.java:270)
[ERROR]     at com.vaadin.sass.internal.ScssStylesheet.compile(ScssStylesheet.java:239)
[ERROR]     at com.vaadin.sass.SassCompiler.main(SassCompiler.java:58)
1. I'm using external maven build and not the Eclipse build process, so the following ticket does not apply http://dev.vaadin.com/ticket/15500
2. I've made the tweak from vaadin-client-compiled to vaadin-client-compiler as suggested in stackoverflow with no success.
   http://stackoverflow.com/questions/27716171/error-when-to-compile-my-theme-with-vaadin-7-3-and-valo-theme
3. The build completes with success, but there is still an error during the build which is disconcerting.
4. Question
   Is there a <inherits> value that should be inserted into the AppWidgetSet.gwt.xml?

Traditionally, when inserting other add-ons into the maven pom.xml, resources are automatically inserted into the AppWidgetSet.gwt.xml during the build process.

Thanks,
Malcolm

**Comment by bdunn44** [comment]
Have you tried using the addon after the build succeeds?

I don't believe any entries would be added to your widgetset because one is not provide by this addon. No widgetset recompile is required to use it. Included is a SASS stylesheet (_font-awesome.scss) which should be compiled along with your theme and two classes. I'm not sure why Maven can't seem to find the stylesheet. Are you sure it's on your classpath when building the project?

**Comment by malcolmdavis** [comment]
Build: I do a complete & successful build prior to adding fontawesomelabel to the maven pom.

Classpath: fontawesomelabel is not showing up in my local maven repository.

I suspect there is an issue on how Vaadin has setup their addons repository.

I have asked a forum question regarding the issue at:
https://vaadin.com/forum#!/thread/9189042

Once I have clarification, I will try again.

Thank you,
Malcolm

**Comment by malcolmdavis** [comment]
I was looking in the wrong place in my local Maven repository.  

A 389K fontawesomelabel-1.1.7.jar  is located at /org/vaadin/addons/fontawesomelabel/1.1.7

Thank you,
Malcolm
