### ISSUE TITLE
SCSS missing @mixin element

### ISSUE THREAD

**Issue by deckerra** [bdunn44/FontAwesome-Vaadin#2]
When I compile my theme I get this error: com.vaadin.sass.internal.parser.ParseException: Mixin Definition: _font-awesome not found because the _font-awesome.scss does not contain an @mixin _font-awesome {} element.

**Comment by bdunn44** [comment]
What version of Vaadin are you using?

**Comment by deckerra** [comment]
Vaadin 7.4.3 and 1.1.8 of the add on.

Thank You
Rob

**Comment by bdunn44** [comment]
I'm unable to reproduce this in my environment. Are you using the latest version of the Eclipse plugin? Please send the contents of your `addons.scss` file.

Thanks,
Bryson

**Comment by deckerra** [comment]
I am not using the Eclipse plugin so I cannot speak to how that compiles theme. I am using the Sass theme compiler: com.vaadin.sass.SassCompiler. This is what is producing the error. This gets pulled by ivy.xml :



```
                            <dependency org="com.vaadin" name="vaadin-themes" rev="&vaadin.version;">
```

Then I have an ant script that calls the compiler:

<target name="-compile-theme-1" if="theme.name">
                  <mkdir dir="${war.content}/VAADIN/themes/${theme.name}"/>
                  <java classname="com.vaadin.sass.SassCompiler" failonerror="yes" fork="yes">
                                <classpath refid="webapp.lib.files"/>
                                <jvmarg value="-Djava.awt.headless=true"/>
                                <arg value="${theme.dir}/${theme.name}/styles.scss"/>
                                <arg value="${war.content}/VAADIN/themes/${theme.name}/styles.css"/>
                  </java>
                </target>

The addon.scss looks like this and is generated by the addons:

/\* This file is automatically managed and will be overwritten from time to time. _/
/_ Do not manually edit this file. */

/\* Provided by font-awesome-label-1.1.8.jar */
@import "../../../VAADIN/addons/font-awesome-4.3.0/css/_font-awesome.scss";

/\* Provided by ContextMenu-4.5.0.jar */
@import "../../../VAADIN/themes/contextmenu/contextmenu.scss";

/\* Import and include this mixin into your project theme to include the addon themes */
@mixin addons {
                @include _font-awesome;
                @include contextmenu;
}

If I look in jar for the contextmenu addon scss it has the @mixin contextmenu wrapper:

@mixin contextmenu {
….
}

But the _font-awesome.scss looks like it just the font-awesome.scss and has no @mixin _font-awesome {} wrapping it so the @include _font-awesome in the addons.scss is never found:

/*!
-  Font Awesome 4.3.0 by @davegandy - http://fontawesome.io - @fontawesome
-  License - http://fontawesome.io/license (Font: SIL OFL 1.1, CSS: MIT License)
  _/
  /_ FONT PATH
- -------------------------- */
  @font-face {
  font-family: 'FontAwesomeLabelAddon';
  src: url('../fonts/fontawesome-webfont.eot?v=4.3.0');
  src: url('../f

etc.

I think it should look like this:

@mixin _font-awesome {
/*!
-  Font Awesome 4.3.0 by @davegandy - http://fontawesome.io - @fontawesome
-  License - http://fontawesome.io/license (Font: SIL OFL 1.1, CSS: MIT License)
  _/
  /_ FONT PATH
- -------------------------- */
  @font-face {
  font-family: 'FontAwesomeLabelAddon';
  src: url('../fonts/fontawesome-webfont.eot?v=4.3.0');
  src: url('../f

etc.

}
Thank You
Rob

**Comment by bdunn44** [comment]
The Plugin uses the same class to compile the theme and I'm unable to reproduce this error in my environment. There haven't been any reports of this error until now, either, although it would be more semantically correct to wrap the CSS in an @mixin declaration. 

I'll work on a release with this small change, although since I'm unable to reproduce the error I can't guarantee it will work for you.

**Comment by bdunn44** [comment]
The version 1.1.9 release should resolve this issue. Please try it out and report back!

Thanks,
Bryson

**Comment by deckerra** [comment]
This doesn’t work because you added to the font-awesome.scss:

@mixin font-awesome {

does not match what it is called in addon.scss:

/\* Provided by font-awesome-label-1.1.8.jar */
@import "../../../VAADIN/addons/font-awesome-4.3.0/css/_font-awesome.scss";

In fact the whole VAADIN/addons directory structure has change from version 1.1.8 where you had a css and fonts folders underneath font-awesome-4.3.0 to putting everything flat under font-awesome-4.3.0 in 1.1.9. And .scss filename changed from _font-awsome.scss to font-awesome.scss.

Thank You
Rob

**Comment by bdunn44** [comment]
It looks like your `addons.scss` file is still referencing verison 1.1.8. You're right, the directory structure did change, which is why the manifest and scss file in version 1.1.9 were updated accordingly. 

I'm not sure how you manage your `addons.scss` file, but the Eclipse plugin automatically updates it based on the addons it finds in the classpath (it specifically looks for the `Vaadin-Stylesheets` entry in the manifest). You'll either need to update your `addons.scss` file manually or re-run whatever build process you have that updates it. You're new file will look something like this:

``` sass
/* Provided by font-awesome-label-1.1.9.jar */
@import "../../../VAADIN/addons/font-awesome-4.3.0/font-awesome.scss";


/* Import and include this mixin into your project theme to include the addon themes */
@mixin addons {
    @include font-awesome;
}
```

**Comment by deckerra** [comment]
That fixed the issue. Not sure why addons.scss wasn’t getting updated. It calls “Addon Style Builder” but kept failing with a MALFORMED error when reading the jar. I had to exit eclipse and start it again to get it work. Must have been some kind of caching thing.

Thank You
Rob
