### ISSUE TITLE
Update to 4.4

### ISSUE THREAD

**Issue by kiru** [bdunn44/FontAwesome-Vaadin#3]
Would be nice to have this addon updated to version 4.4 of FontAwesome.

**Comment by kiru** [comment]
Closed issue - since the official vaadin FontAwesome class has updated to 4.4: https://github.com/vaadin/vaadin/blob/master/server/src/com/vaadin/server/FontAwesome.java

**Comment by bdunn44** [comment]
Pull request #4 has upgraded this library to FontAwesome 4.5
